services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./database:/data/db
    ports:
      - "27017:27017"
    container_name: "mongodb"
    hostname: mongo
    networks:
      - interna

networks:
  interna:
     driver: bridge
